title: John Shepard
#logo: /assets/img/headshot_circle.png
#description: test below image
#show_downloads: true
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
